create table "public"."user_market_collateral" (
    "id" bigint generated by default as identity not null,
    "updated_at" timestamp with time zone not null default now(),
    "balance" bigint,
    "market_id" text,
    "user_address" text
);


alter table "public"."user_market_collateral" enable row level security;

CREATE UNIQUE INDEX user_market_collateral_pkey ON public.user_market_collateral USING btree (id);

alter table "public"."user_market_collateral" add constraint "user_market_collateral_pkey" PRIMARY KEY using index "user_market_collateral_pkey";

alter table "public"."user_market_collateral" add constraint "user_market_collateral_market_id_fkey" FOREIGN KEY (market_id) REFERENCES market(id) not valid;

alter table "public"."user_market_collateral" validate constraint "user_market_collateral_market_id_fkey";

alter table "public"."user_market_collateral" add constraint "user_market_collateral_user_address_fkey" FOREIGN KEY (user_address) REFERENCES "user"(address) not valid;

alter table "public"."user_market_collateral" validate constraint "user_market_collateral_user_address_fkey";

grant delete on table "public"."user_market_collateral" to "anon";

grant insert on table "public"."user_market_collateral" to "anon";

grant references on table "public"."user_market_collateral" to "anon";

grant select on table "public"."user_market_collateral" to "anon";

grant trigger on table "public"."user_market_collateral" to "anon";

grant truncate on table "public"."user_market_collateral" to "anon";

grant update on table "public"."user_market_collateral" to "anon";

grant delete on table "public"."user_market_collateral" to "authenticated";

grant insert on table "public"."user_market_collateral" to "authenticated";

grant references on table "public"."user_market_collateral" to "authenticated";

grant select on table "public"."user_market_collateral" to "authenticated";

grant trigger on table "public"."user_market_collateral" to "authenticated";

grant truncate on table "public"."user_market_collateral" to "authenticated";

grant update on table "public"."user_market_collateral" to "authenticated";

grant delete on table "public"."user_market_collateral" to "service_role";

grant insert on table "public"."user_market_collateral" to "service_role";

grant references on table "public"."user_market_collateral" to "service_role";

grant select on table "public"."user_market_collateral" to "service_role";

grant trigger on table "public"."user_market_collateral" to "service_role";

grant truncate on table "public"."user_market_collateral" to "service_role";

grant update on table "public"."user_market_collateral" to "service_role";


