name: Lint Code

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Run Lint
      - name: Run Lint
        run: bun run lint
