- name: Supabase Database Branching Preview
  uses: 0xBigBoss/supabase-branch-gh-action@v1
  with:
    supabase_token: ${{ secrets.SUPABASE_TOKEN }}
    supabase_url: ${{ secrets.SUPABASE_URL }}
    branch_name: ${{ github.ref_name }}
    branch_type: preview
- name: Get result
  run: | 
    echo "ref=${{steps.supabase-branch.outputs.ref}}"
    echo "api_url=${{steps.supabase-branch.outputs.api_url}}"
    echo "graphql_url=${{steps.supabase-branch.outputs.graphql_url}}"
    echo "db_host=${{steps.supabase-branch.outputs.db_host}}"
    echo "db_port=${{steps.supabase-branch.outputs.db_port}}"
    echo "db_user=${{steps.supabase-branch.outputs.db_user}}"
    echo "db_password=${{steps.supabase-branch.outputs.db_password}}"
    echo "jwt_secret=${{steps.supabase-branch.outputs.jwt_secret}}"
    echo "anon_key=${{steps.supabase-branch.outputs.anon_key}}"
    echo "service_role_key=${{steps.supabase-branch.outputs.service_role_key}}"