name: Deploy to Vercel [Custom]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GH_TOKEN: ${{ github.token }}

on:
  push:
    branches:
      - "*"
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'vercel-opynco'
    steps:
      - uses: actions/checkout@v2
      - name: Determine Deployment Environment
        id: prod_or_not
        run: |
          if [ "${{ github.ref }}" == 'refs/heads/main' ]
          then
              echo "vercel-args=--prod" >> $GITHUB_OUTPUT
          else
              echo "vercel-args=" >> $GITHUB_OUTPUT
          fi
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes ${{steps.prod_or_not.outputs.vercel-args}} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: |
          vercel ${{steps.prod_or_not.outputs.vercel-args}} -t ${{ secrets.VERCEL_TOKEN }} -m githubCommitSha=${{ github.sha }} -m githubCommitAuthorName=${{ github.actor }} -m githubCommitAuthorLogin=${{ github.actor }} -m githubDeployment=1 -m githubOrg=opynfinance -m githubCommitOrg=opynfinance -m githubCommitMessage="${{ github.event.head_commit.message }}" -m githubCommitRef=${{ github.ref_name }} --scope ${{ secrets.VERCEL_ORG_ID }} --force --yes > temp.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "Deployed to: $(<temp.txt )" || echo "Could not comment"
          rm temp.txt